### PR TITLE
Added Mekanism Tools and Armour (+ Fixes)

### PR DESCRIPTION
**Pull request by Eleiyas**
* All Mekanism Tools and Armour added.

* Fixed Swords having transparent pixels.

* Fixed Obsidian Nugget being "base" colour.

### CODE REVIEW

**Review by zISKo666 — APPROVED** [review]
Looking good to me. :)
Thanks for your work.

**Review by artdude543 — CHANGES_REQUESTED** [review]
Here is my feedback:

- assets/soartex_base/textures/items/armor/glowstone/leggings.png: Is too dark 
- assets/soartex_base/textures/items/armor/lapis/chestplate.png: Borderline being too dark, brighten a tad in the armpit areas.
- assets/soartex_base/textures/items/armor/lapis/helmet.png: Too dark inside the helmet.
- assets/soartex_base/textures/items/tool/glowstone/*: The contrast needs adjusting to not be as bright as they are all currently.

Otherwise, the rest looks good! Thank you for your contribution(s)

**Comment by Eleiyas** [comment]
> Here is my feedback:
> 
> * assets/soartex_base/textures/items/armor/glowstone/leggings.png: Is too dark
> * assets/soartex_base/textures/items/armor/lapis/chestplate.png: Borderline being too dark, brighten a tad in the armpit areas.
> * assets/soartex_base/textures/items/armor/lapis/helmet.png: Too dark inside the helmet.
> * assets/soartex_base/textures/items/tool/glowstone/*: The contrast needs adjusting to not be as bright as they are all currently.
> 
> Otherwise, the rest looks good! Thank you for your contribution(s)

Hi Artdude,

I know that the glowstone stuff isn't fantastic as I had to try and find a colour that was unique enough, so that it wouldn't be confused with either the standard Gold Armour/Tools or the Electrum Armour/Tools, despite all 3 sharing the same pallette.

I will try and sort something out as I know for a fact that the shovel is pretty bad in its current state. Maybe someone more... savvy(?) could help me on this?

As for the lapis, I have to disagree, the interior of the helmet should be dark, as should the armpits on the chestplate, as they would be doused in shadows; again, I also did not want confusion between the lapis set and the osmium set.

Thirdly, these are only the item textures. The actual player-modeled armour is part of the Mekanism mod, so would be added to Soartex Modded 1.12.2, not Soartex Base 1.12.2.

I can send you those via e-mail if you wish to check, or I can post those on imgur quickly for you to glance at :)

**Comment by artdude543** [comment]
What's the status of this PR? I can take a look at the shovels when I get back home to a desktop. Currently stuck in another country due to this nice virus. So limited resources; but I'll take the other comments on board just if you can tweak the glowstone stuff a tad that'll be fine.

**Comment by Eleiyas** [comment]
> What's the status of this PR? I can take a look at the shovels when I get back home to a desktop. Currently stuck in another country due to this nice virus. So limited resources; but I'll take the other comments on board just if you can tweak the glowstone stuff a tad that'll be fine.

I can try and re-do the glowstone stuff for sure.

Other things I think are good as-is.

**Comment by Eleiyas** [comment]
I have now re-done all the glowstone stuff to be more gold-like in texture and way less "omg my eyes" in contrast and brightness.

hope these are now good!

**Comment by artdude543** [comment]
Okay, I like the changes! Thanks for your contributions!

**Pull request merged**
