### PR TITLE
Deepslate Ores

### PR DESCRIPTION
**Pull request by ScottDTA**

### CODE REVIEW

**Comment by Shoeboxam** [comment]
I'm surprised this repo wasn't included in your permissions already. Fixed!

**Comment by ScottDTA** [comment]
Thank you.

**Comment by Shoeboxam** [comment]
No, thank you!

**Comment by ScottDTA** [comment]
How do we go about pushing a release for 1.18 once I have most of it done?

**Comment by Shoeboxam** [comment]
For now, just send me a message and I can prep a pack and upload it. I had this process nearly automated, so that other people can cut releases... it seems I should finish that little side project.

**Comment by ScottDTA** [comment]
if you get the automated process going, that would be great.   I would prefer to push a release soon and do updates as I get more ported and/or created.   Also need to look at possible starting 1.19 and with an auto system, I might even push some of the older versions.  There has been activity on the repo's for them, but not included in the current releases.

**Pull request merged**
